name: 'Deploy'

on:
  push:
    branches: [ main ]

jobs:
  deploy-uat:
    name: 'Deploy UAT'
    runs-on: ubuntu-latest
    environment: uat
    
    steps:
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.0"

    - name: Deploy UAT
      run: |
        cd environments/uat
        terraform init
        terraform apply -auto-approve

  deploy-prod:
    name: 'Deploy PROD'
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment: prod
    
    steps:
    - uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.0"

    - name: Deploy PROD
      run: |
        cd environments/prod
        terraform init
        terraform apply -auto-approve
